### PR TITLE
Put back enable

### PR DESCRIPTION
**Pull request by ggordan**
PR to view changes being made in the development branch.

### CODE REVIEW

**Comment by ggordan** [comment]
@poshaughnessy @bkspace 

So for the last commit a972088 Sammy found a potentially great solution to avoiding the disconnect delay. Which basically triggers disconnect once we receive the 'low level' callback which is around 30-100ms after we close the `BluetoothGatt`. We tested this somewhat on the good Vodafone phone and we didn't see any failures, however we'd need to test this thoroughly on all the devices we have to ensure that it is in fact working well on slow devices too since `BluetoothGatt.close()` could potentially be slower on bad hardware.

Sammy and I were discussing this yesterday, and while we can (and should) do a release with this version, or potentially one where the disconnect callback delayed is reduced to around 1000ms, we should be aware, and let the client know, that getting failures more often is to be expected. So it's a matter of weighing up reliability vs speed, or finding that sweet spot.

^ This could all be void though if todays testing yields positive results.

N.B. This is incomplete at the moment, since we will always trigger a success callback whenever we're disconnected, which obviously isn't what we want. I'll be adding in the `expectDisconnect` this morning.

**Comment by export-mike** [comment]
🎉

**Comment by bkspace** [comment]
:trollface:

**Comment by export-mike** [comment]
🥇

**Comment by bkspace** [comment]
💯

**Comment by export-mike** [comment]
image

**Comment by ggordan** [comment]
👀

**Comment by export-mike** [comment]
image

**Pull request closed without merging**
